apiVersion: v1
kind: Pod
metadata:
  name: appa-pod
  labels:
    app: appa
    ver: v1
spec:
  containers:
  - name: appa-container
    image: shekeriev/k8s-appa:v1
    ports:
    - containerPort: 80
