apiVersion: v1
kind: Service
metadata:
  name: appa-svc
  labels:
    app: appa
    ver: v1
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: appa
    ver: v1
