apiVersion: apps/v1
kind: Deployment
metadata:
  name: appa-deploy
spec:
  replicas: 10
  selector:
    matchLabels: 
      app: appa
      ver: v1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: appa
        ver: v1
    spec:
      containers:
      - name: appa-container
        image: shekeriev/k8s-appa:v1
        ports:
        - containerPort: 80 
